version: 2

sources:
  - name: tpch_sample
    database: tpch
    schema: public 
    #TPCH_SF{{ var('tpch_size', 10) }}
    tables:
      - name: lineitem
      - name: customer
      - name: orders
      - name: partsupp
      - name: supplier
      - name: part
      - name: nation
      - name: region
